# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xkUKMkSt7VOymGiGSYmQQjw26130PsAy
"""

#instalação da API gspread — responsável por permitir a interação dos trechos de código python com as planilhas do Google.
 !pip install gspread --upgrade

#importando as bibliotecas para autenticação e acesso ao Google Sheets
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

#importando o arquivo do google sheets
spreadsheet = gc.open('Investimentos')

#obtendo a pagina necessária
df = spreadsheet.sheet1

import pandas as pd

df_investimentos = pd.DataFrame(df.get_all_records())
print(df_investimentos)

listUsers = df_investimentos[['Nome','Capital','Valor mensal investido']]
print(listUsers)
valor_investido = listUsers['Valor mensal investido']

!pip install openai

openai_api_key = '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'

import openai

openai.api_key = openai_api_key

def generate_ai_simulation(valor_investido):

 completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo-16k",
    messages=[
      {
        "role": "system",
        "content": "Financial Consultant"
      },
      {
        "role": "user",
        "content": f"sugestão de investimento para aplicação mensal de {valor_investido}   (máximo de 50 caracteres)"
      },

    ]
  )
 return completion.choices[0].message.content.strip('\"')

sugestao_investimento = []


for valor in valor_investido:
    sugestao = generate_ai_simulation(valor)
    print(sugestao)
    sugestao_investimento.append(sugestao)

#inserindo nova coluna e valores no dataframe
df_investimentos.insert(6,'Sugestao de Investimento',sugestao_investimento)

#criando uma nova coluna na planilha
df.update('F1','Sugestão de Investimentos')

#atualizando a planilha com os dados do dataframe
df.update([df_investimentos.columns.values.tolist()] + df_investimentos.values.tolist())